### ISSUE TITLE
msppg.h

### ISSUE THREAD

**Issue by enrfbezo** [simondlevy/MSPPG#2]
Hi Simon,
This might be a silly question but i cannot find "msppg.h" anywhere in your msppg directory files. Could you please advise?
Thank you in advance and happy new year,
Fred

**Comment by simondlevy** [comment]
Once you run the msppg.py script, you will see msppg.h in output/c/msppg.

On Fri, Jan 8, 2016 at 6:29 PM, enrfbezo notifications@github.com wrote:

> Hi Simon,
> This might be a silly question but i cannot find "msppgh" anywhere in your
> msppg directory files Could you please advise?
> Thank you in advance and happy new year,
> Fred
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/simondlevy/MSPPG/issues/2.

## 

Simon D. Levy
Professor
Computer Science Department
407 Parmly Hall
Washington & Lee University
Lexington, VA 24450

540-458-8419 (voice)
540-458-8255 (fax)

**Comment by enrfbezo** [comment]
Thank you Simon. It's working great.
